### ISSUE TITLE
Sound Files Don't Show When Trying to Add Sound Command

### ISSUE THREAD

**Issue by PoisonFlame** [DandyEnders/Braille-Project#7]
<h1>Sound Files Don't Show When Trying to Add Sound Command</h1>

<h2>General Information</h2>
OS: Windows 10 Home <br>
Java Version: 9.0.4 <br>
Component: Listview of "create sound file dialog"
  
<h2>Description</h2>
<p>This bug occurs on the release version 1.0 that was released on February 23rd, 2018. This bug occurs when trying to add a new sound command from the create scenario screen. Although the voice has been recorded through the voice recorder,  the create sound command in the create scenario screen shows no sound files present which effectively doesn't allow the end-user to use the add a sound file command.</p>

<h2>Steps to Reproduce</h2>
<b>Assuming a Sound File is created from the in-app sound voice recorder:</b> <br>
1.) Open the Authoring App<br>
2.) Click on the "Scenario Editor" Button<br>
3.) Click on the "Create a New Scenario" Button<br>
4.) Click on the "Create a command" Button<br>
5.) From the command type drop-down, choose first item "/~sound"<br>
6.) Click on the first argument drop-down to choose a sound file name<br>
<br>
<b>If the sound file is not created through the in-app sound voice recorder:</b><br>
1.) Open the Authoring App<br>
2.) Click on the "Voice Recorder" Button<br>
3.) Click "Record Voice" Button<br>
4.) Name the audio file<br>
5.) Talk, record the audio<br>
6.) Click the "Record Voice" Button again to end the recording<br>
7.) Your newly created file should appear in the voice file list<br>
8.) Exit the voice recorder<br>
9.) Go back to the main screen and click on "Scenario Editor" Button<br>
10.) Click on the "Create a New Scenario" Button<br>
11.) Click on the "Create a command" Button<br>
12.) From the command type drop-down, choose first item "/~sound"<br>
13.) Click on the first argument drop-down to choose a sound file name<br>

<h2>Actual Results</h2>
Empty drop-down with no current sound files present.
<h2>Expected Results</h2>
Drop-down should have entries of sound files created through the voice recorder.

<h2>Summary</h2>
These results will show that the drop-down for the first argument of choosing a sound file name is empty although a sound file has been created through the voice recorder.

<h2>Relevant Screenshots</h2>
<img src='https://rpsh.me/xoleminu'>
<p>These files should be present.</p>
<img src='https://rpsh.me/masicete'>
<p>This is the given result showing that the files are indeed not present.</p>

**Comment by DandyEnders** [comment]
Now it properly shows the sound file on the voice recorder list.
