### ISSUE TITLE
Move command down resets to top of list each click

### ISSUE THREAD

**Issue by connordear** [DandyEnders/Braille-Project#8]
# Move command down button resets to the top of the list each time

## Summary
Each time I click the move command down button, the list selects the top item again. This causes moving an item from the top of the list to the bottom of the list to be labor intensive.

## Technical Information
**OS** : CentOS Linux 7
**Java Version** : version 8 update 161 Build 1.8.0_144
**Used Release Version** : 1.0 

## Description
"Move it down" command resets selection to top item each time it is pressed.

# Steps to Reproduce

1. Open the Braille Author.
2. Click on Scenario Editor
3. Create new scenario.
4. Add new commands to the scenario maker
5. Attempt to move the top command to the bottom, each time the move it down button is pressed, the first item becomes selected.

## Expected Results
Expected that the item would remain selected so that the user can continue rearranging the movement of the initially selected command.

## Actual Results
Upon pressing the button, the selected command was changed to the first item in the list.

**Comment by DandyEnders** [comment]
The commands on the scenario maker now properly moves the selected command up and down with proper highlights on selected command.
