### ISSUE TITLE
App does not show details about an error when loading a scenario

### ISSUE THREAD

**Issue by samank3** [DandyEnders/Braille-Project#9]
# Summary
Upon opening the app, two scenarios already appear on the left pane. However, when clicking "Load Scenario" and selecting a factory scenario, an error dialogue appears. The error dialogue does not explain what the problem is, rather referring the user to the "/error/ folder". When the user opens the user folder in the release's folder, it is empty.

# Technical Information
OS: Windows 10 Home
Java Version: Java 8 Update 161
Release Version: 1.0
Component: Load Scenario

# Steps to Reproduce Bug
1. Run the Authoring.exe app
2. Select 'Scenario Editor'
3. Select 'Load Scenario'
4. Choose a factory scenario text file that comes pre-loaded
5. Error dialogue will appear upon selecting the text file

# Screenshot of Bug
<img width="960" alt="screenshot 81" src="https://user-images.githubusercontent.com/32426683/37070695-c6caa4e2-2186-11e8-9a32-06f47d1c037e.png">

# Expected Result
Error should not appear when loading an already existing scenario. If this is an implementation that the developer intends for, a more detailed error dialogue should appear informing the user of the correct way to load a scenario. It should be intuitive without having to read the user manual.

# Actual Result
A error dialogue appears, informing the user that _the editor has failed to load some of the files. The reasons will be stated on /error/ folder._ Error folder within the developer's release remains empty after this error 

**Severity** Normal
**Priority** 2

**Comment by DandyEnders** [comment]
Now the program properly displays reasons for failure.
